# Generated by Django 5.2.7 on 2025-10-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
