# Generated by Django 5.2.7 on 2025-10-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_deal',
            field=models.BooleanField(default=False),
        ),
    ]
