# Generated by Django 5.2.7 on 2025-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_best_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_deal_star',
            field=models.BooleanField(default=False),
        ),
    ]
